---
abstract: 'bundle up multiple type constraint libraries'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
  Test::Requires: 0.06
  Test::TypeTiny: 0.028
  Types::Standard: 0.028
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Type-Libraries
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Type::Libraries:
    file: lib/Type/Libraries.pm
    version: 0.001
requires:
  Type::Library: 0.028
  Type::Utils: 0.028
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Type-Libraries/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-Libraries
  homepage: https://metacpan.org/release/Type-Libraries
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-type-libraries
version: 0.001
